remote_theme: jekyll/minima
logo: _assets/logo.png
title: ASDRoNet 2024
description: Algorithmic Solutions for Drone- and Robot-based Networks
minima:
  skin: solarized-light
author: ASDRoNet © 2024

